### ISSUE TITLE
useCustomPropertyStyleSheet cannot be resolved when CSS custom properties are used

### ISSUE THREAD

**Issue by aleksitaipale** [jacobp100/cssta#50] opened 2021-02-09 09:17 UTC
Bundler seems to be unable to resolve `useCustomPropertyStyleSheet` when CSS custom properties ("variables") are used. Upon further investigation, there is no such file under `cssta/runtime/useCustomPropertyStyleSheet`, even though it is called in multiple places in `babel-plugin-cssta`. Is the CSS variable feature broken, or does using the feature require some extra configuration in e.g. Babel?

So, for example the scenario outlined in [Theming](https://github.com/jacobp100/cssta#%EF%B8%8F-theming) does not work:

```js
const Inverted = cssta(View)`
  background-color: black;
  --primary: white;
`;

const ThemedText = cssta(Text)`
  color: var(--primary, black);
  border: 1px solid var(--primary, black);
  padding: 6px 12px;
`;

<ThemedText>I black text</ThemedText>;
<Inverted>
  <ThemedText>I am white text on a black background!</ThemedText>
</Inverted>;
```

**Comment by jacobp100** [comment] 2021-02-09 09:32
I have a feeling what's on master isn't published on npm. You could try cloning this repo, running `yarn && yarn build`, then `yarn add <path-to-local-repo>` or `npm install <path-to-local-repo>`

It's been a while since I worked on this :sweat_smile:

**Comment by aleksitaipale** [comment] 2021-02-09 10:39
Thank you for the quick answer! I see, so I surmise the repo is not and will not be in active development for the time being? :D I guess I could've deduced that from the last update as well, but just asking.

I tried your method and installed both the babel plugin as well as cssta itself by cloning, but no dice. It just seems that there is no file called `useCustomPropertyStyleSheet` under [`runtime/`](https://github.com/jacobp100/cssta/tree/master/runtime). It seems that there [used to be](https://github.com/jacobp100/cssta/blob/b914f742b7b2f37619e640cdcac9d7e0b1cf6108/runtime/useCustomPropertyStyleSheet.js), but it [was removed](https://github.com/jacobp100/cssta/commit/8339b0f6e8b50745cd0466768db7be8185aad52d#diff-d92c6a81b2ff50096bcda80885427d1f59a25b5f483f7055523504925d16ab23), and I guess replaced with [`useCustomPropertyStyle.js`](https://github.com/jacobp100/cssta/blob/8339b0f6e8b50745cd0466768db7be8185aad52d/runtime/useCustomPropertyStyle.js)...

Actually, I'd wager that the problem is that the cssta babel plugin has `cssta 0.9.0` as [a dependency](https://github.com/jacobp100/babel-plugin-cssta/blob/master/package.json#L7). That version seems to still have the old file name. :thinking:

**Comment by jacobp100** [comment] 2021-02-09 11:03
What's requiring that file? I can't seem to find it?

Did you restart the metro bundled with --resetCache?

**Comment by aleksitaipale** [comment] 2021-02-09 12:02
Yep! I did, but that didn't change the situation.

So basically what happens is this, I think:
* I install `babel-plugin-cssta`
* It has `cssta 0.9.0` as dependency, and fetches that under `myProject/node_modules/babel-plugin-cssta/node_modules/cssta`
* Babel plugin requires "itself" from that `cssta 0.9.0` with this in [index.js](https://github.com/jacobp100/babel-plugin-cssta/blob/master/index.js)

```
module.exports = require("cssta/babel-plugin");
```

And under, for example `myProject/node_modules/babel-plugin-cssta/node_modules/cssta/compiler/babel/styleSheet/index.js`, we have:

```
  const useCustomPropertyStyleSheetImport = getOrCreateImport(
    babel,
    path,
    "cssta/runtime/useCustomPropertyStyleSheet"
  );
```

-----

Using the VSCode search, these are the places I find the results in:

```
myProject/node_modules/babel-plugin-cssta/node_modules/cssta/compiler/__tests__/build.js
  280,12:     import useCustomPropertyStyleSheet from 'cssta/runtime/useCustomPropertyStyleSheet';
  280,60:     import useCustomPropertyStyleSheet from 'cssta/runtime/useCustomPropertyStyleSheet';
  284,22:       const styles = useCustomPropertyStyleSheet(unresolvedStyleTuples, customProperties);

myProject/node_modules/babel-plugin-cssta/node_modules/cssta/compiler/__tests__/integration.js
  115,10:     var _useCustomPropertyStyleSheet = _interopRequireDefault(require(\\"cssta/runtime/useCustomPropertyStyleSheet\\"));
  115,88:     var _useCustomPropertyStyleSheet = _interopRequireDefault(require(\\"cssta/runtime/useCustomPropertyStyleSheet\\"));
  132,27:       const styles = (0, _useCustomPropertyStyleSheet.default)(unresolvedStyleTuples, customProperties);

myProject/node_modules/babel-plugin-cssta/node_modules/cssta/compiler/babel/styleSheet/index.js
  54,9:   const useCustomPropertyStyleSheetImport = getOrCreateImport(
  57,20:     "cssta/runtime/useCustomPropertyStyleSheet"
  63,22:     t.callExpression(useCustomPropertyStyleSheetImport, [

myProject/node_modules/babel-plugin-cssta/node_modules/cssta/docs/technical-details.md
  133,156: Custom properties are supported by a `useCustomProperties` hook. In addition, everything that needs custom properties has an additional hook. Styles have `useCustomPropertyStyleSheet`, and animations and transitions have `useCustomPropertyShorthandParts` (more on that later).
  152,8: import useCustomPropertyStyleSheet from "cssta/runtime/useCustomPropertyStyleSheet";
  152,56: import useCustomPropertyStyleSheet from "cssta/runtime/useCustomPropertyStyleSheet";
  158,18:   const styles = useCustomPropertyStyleSheet(
```

**Comment by jacobp100** [comment] 2021-02-09 13:02
Oh yeah, the Babel plugin does require cssta. Delete node_modules/babel-plugin-cssta/cssta and see if that works? So you only have one copy of cssta in your node modules

**Comment by aleksitaipale** [comment] 2021-02-10 08:12
Unfortunately that doesn't work either, because then the babel plugin doesn't find any cssta. :( The closest I've got is with these steps:

* clone `cssta` to a local folder
* clone `babel-plugin-cssta` to a local folder
* set the dependency to refer to the local `cssta` inside `babel-plugin-cssta/package.json`
* `yarn && yarn build` the local `cssta``
* `yarn` the local `babel-plugin-cssta`
* `yarn` my own project

But the error just changes:

> Unable to resolve module cssta/runtime/useCustomPropertyStyles from myProject/components/button.js: cssta/runtime/useCustomPropertyStyles could not be found within the project.

This makes sense, since there's no such file as useCustomPropertyStyle**s**, only [useCustomPropertyStyle](https://github.com/jacobp100/cssta/blob/master/runtime/useCustomPropertyStyle.ts). But there are references to both ones, "with s" (e.g. [`cssta/index.ts#L74`](https://github.com/jacobp100/cssta/blob/master/compiler/babel/styleSheet/index.ts#L74)) and "without s" (e.g. [`cssta/runtime/__tests__/useCustomPropertyStyle.ts#L4`](https://github.com/jacobp100/cssta/blob/master/runtime/__tests__/useCustomPropertyStyle.ts#L4)). I then tried replacing every import of the "styles"-file with the "style"-file, but then get an entirely different error, something about an invalid hook call, so that's probably not the right way to fix it anyway.

**Comment by jacobp100** [comment] 2021-02-10 09:19
Run `yarn why cssta` in your project and copy+paste the result

**Comment by aleksitaipale** [comment] 2021-02-10 09:27
Check, here goes:

```
➜  myProject yarn why cssta
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "cssta"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "cssta@0.9.7"
info Has been hoisted to "cssta"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "babel-plugin-cssta#cssta"
info Disk size without dependencies: "198.23MB"
info Disk size with unique dependencies: "201.67MB"
info Disk size with transitive dependencies: "205.11MB"
info Number of shared dependencies: 20
✨  Done in 1.84s.
```

**Comment by jacobp100** [comment] 2021-02-10 11:28
Okay, so you definitely have the one copy.

I think the issue is fixed by me just releasing what's on master, but I want to check your project first. Could you,

- Add these dependencies to your project: https://github.com/jacobp100/cssta/blob/master/package.json#L57-L60
- Build the project locally
- In your `node_modules/cssta`, delete `compiler`, `runtime`, `babel-plugin.js` and `native.macro.js`
- Copy these back over from your locally built project
- In your RN project, run `yarn start --reset-cache`

**Comment by aleksitaipale** [comment] 2021-02-10 13:55
I see! Just to be clear, I'm already referring to the locally built project in my RN project, like this:

`"cssta": "/Users/aleksitaipale/Documents/Coding/cloned_repos/cssta"`

And that locally built `cssta` already has those dependencies you mentioned. Should I still delete and copy those files separately from the locally built cssta to the `node_modules/cssta` by hand?

**Comment by jacobp100** [comment] 2021-02-10 13:59
Oh I see. You could try from npm and replacing the folders so there's definitely no issues with symlinks

I'm kinda confused because the find and replace you pasted shows something different to what's on the master branch here

**Comment by aleksitaipale** [comment] 2021-02-10 14:09
When I did the search above (in [this comment](https://github.com/jacobp100/cssta/issues/50#issuecomment-775888766)), I still had the npm-installed versions. If I have those installed, `yarn why cssta` *does* seem to show two different cssta versions. The findings from my search are all from the 0.9.0 version that babel-plugin-cssta has. I'll try replacing both npm-installed csstas by hand-copying from the locally built repo now.

```
➜  myProject yarn why cssta
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "cssta"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "cssta@0.9.7"
info Has been hoisted to "cssta"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "544KB"
info Disk size with unique dependencies: "3.97MB"
info Disk size with transitive dependencies: "7.41MB"
info Number of shared dependencies: 23
=> Found "babel-plugin-cssta#cssta@0.9.0"
info This module exists because "babel-plugin-cssta" depends on it.
info Disk size without dependencies: "452KB"
info Disk size with unique dependencies: "2.09MB"
info Disk size with transitive dependencies: "3.68MB"
info Number of shared dependencies: 19
✨  Done in 0.62s.
```

**Comment by aleksitaipale** [comment] 2021-02-10 14:21
Okay, I tried that:
* Add npm-`cssta` and npm-`babel-plugin-cssta` as dependencies in my RN project; install them
* Build `cssta` locally
* Copy `compiler`, `runtime`, `babel-plugin.js` and `native.macro.js` from local `cssta` to `myProject/node_modules/cssta` and `myProject/node_modules/babel-plugin-cssta/node_modules/cssta`
* `yarn start --reset-cache`
* Run my RN project

And I get the same error as before:

```
Error: Unable to resolve module cssta/runtime/useCustomPropertyStyles from /Users/aleksitaipale/Documents/Coding/myProject/App.js: cssta/runtime/useCustomPropertyStyles could not be found within the project.
```

**Comment by jacobp100** [comment] 2021-02-10 15:25
OH! Duplicate `useCustomPropertyStyle` as `useCustomPropertyStyles` (note the s) - see if that fixes things

**Comment by aleksitaipale** [comment] 2021-02-11 07:45
@jacobp100 - wow, that seems to work!! Would there be a possibility to get all these changes reflected in the npm versions of `cssta` and `babel-plugin-cssta` as well? I.e. getting the babel plugin to use the latest version of cssta, and having the useCustomPropertyStyle work correctly. Then I think cssta could be used in production contexts as well :) It seems there's quite nothing like it in the RN world at least.

![image](https://user-images.githubusercontent.com/10536160/107611557-f180da80-6c4c-11eb-8546-cd9b2f5c3780.png)

And for posterity, the steps were:
* Install npm versions of `cssta` and `babel-plugin-cssta` to my RN project ("`myProject`")
* git clone the `cssta` repo to a local folder, `yarn && yarn build`
* Copy `compiler/`, `runtime/`, `babel-plugin.js` and `native.macro.js` from the local `cssta` folder to `myProject/node_modules/cssta/` and `myProject/node_modules/babel-plugin-cssta/node_modules/cssta/runtime`
* Duplicate `useCustomPropertyStyle` as `useCustomPropertyStyles`, both `.ts` and `.js` files and both inside `myProject/node_modules/cssta/runtime` and `myProject/node_modules/babel-plugin-cssta/node_modules/cssta/runtime`

**Comment by jacobp100** [comment] 2021-02-11 22:04
Ok, you should be able to update cssta and babel-plugin-cssta to 0.10

Let me know if you have any further issues!

**Comment by aleksitaipale** [comment] 2021-02-12 08:36
Ahh... Seems to work! Biiig thanks for all of your help along the way and patience with the different scenarios. 🙌 🙌

**Comment by jacobp100** [comment] 2021-02-12 09:54
I'll close this issue, but feel free to open another if you have more issues!

**Closed by jacobp100** 2021-02-12 09:54 UTC
